"""Generate the initial contract register. Never marks tools complete.
Mode lists are acceptance targets; documentation review remains explicit.
"""
import json
from pathlib import Path
if Path('docs/parity.json').exists():
 raise SystemExit('Parity register already exists. Edit it in place to preserve verified progress.')
BASE='https://cad.onshape.com/help/Content/'
groups={
'Sketching': ('Sketch/sketch_tools.htm', [
('Lines','segment; chained; construction','Draw a 40 × 25 closed profile using four lines'),
('Rectangles','corner; center; three-point','Constrain a 60 × 40 rectangle, then change width to 80'),
('Circles','center-radius; three-point','Constrain a radius-4 circle and extrude a cylinder'),
('Arcs','three-point; tangent; center-point','Close a profile using each arc mode'),
('Ellipses','full ellipse; elliptical arc','Constrain a 30 × 15 ellipse and edit major radius'),
('Polygons','inscribed; circumscribed','Dimension a hexagon to 10 mm across flats'),
('Splines','interpolation; control-point; spline editing','Edit a constrained spline without losing its endpoints'),
('Construction geometry','toggle entities; construction profiles','Extrude a profile while excluding construction entities'),
('Projection','use/project edges; silhouette; intersection','Project a changed upstream edge into a second sketch'),
('Trim','segment removal; boundaries','Trim crossed lines into a closed contour'),
('Extend','nearest boundary','Extend a line to an intersecting arc'),
('Offset','chain; distance; reverse','Offset a mixed line/arc profile by 2 mm'),
('Sketch fillet','radius; trim options','Round a constrained right-angle corner at radius 3'),
('Sketch chamfer','distance; angle','Chamfer a constrained profile and change distance'),
('Sketch patterns','linear; circular; instance count','Pattern a hole at 10 mm spacing and change instance count'),
('Sketch mirror','mirror line; multiple entities','Mirror half a symmetric constrained profile'),
('Dimensions','length; distance; angle; diameter; radius; driven','Resize the bracket using driving dimensions'),
('Expressions','units; arithmetic; variables; trigonometry','Drive a 1 inch length and a variable-based diameter'),
('Geometric constraints','coincident; parallel; perpendicular; tangent; equal; horizontal; vertical; midpoint; normal; pierce; symmetric; concentric; curvature; fix','Solve a mixed line/arc sketch and change one driving dimension'),
('Constraint diagnostics','satisfied; underconstrained; redundant; inconsistent; degenerate','Remove and duplicate constraints; identify conflict IDs'),
]),
'Parametric parts': ('PartStudio/part_studios.htm', [
('Multiple parts','independent solids; shared sketches','Create two parts and selectively modify one'),
('Extrude','solid; surface; thin; new; add; remove; intersect; blind; symmetric; up-to; through-all; direction; draft','Create the base and upright of the mechanical bracket'),
('Revolve','solid; surface; thin; full; angle; symmetric; new; add; remove; intersect','Build a 10/15 mm radius, 20 mm long turned tube'),
('Sweep','solid; surface; profile; path; orientation','Sweep a rectangular profile along a 3D path'),
('Loft','solid; surface; profiles; guides; end conditions','Loft the enclosure through three unequal profiles'),
('Holes','simple; counterbore; countersink; depth; termination; tap','Create a dimensioned hole with a countersink'),
('Threads','external; internal; cosmetic/annotation; pitch','Thread the turned component and check drawing callout'),
('Fillets','edge; face; full-round; constant; variable; tangent propagation','Round selected bracket edges; edit radius'),
('Chamfers','equal distance; two distances; distance-angle; tangent propagation','Chamfer one rim of the turned component'),
('Shell','remove faces; thickness; direction','Hollow the lofted enclosure and change wall thickness'),
('Draft','neutral plane; parting line; direction; angle','Draft an enclosure wall by 3 degrees'),
('Ribs','profile; thickness; direction','Add an upright support rib to the bracket'),
('Booleans','union; subtract; intersect; keep tools','Combine two overlapping analytic boxes'),
('Split','part; face; tool plane/surface','Split a cylinder at its midplane'),
('Transforms','translation; rotation; scale; copy; mate connectors','Move, copy and rotate the second part precisely'),
('Mirrors','part; feature; face; plane','Mirror a bracket hole across its center plane'),
('Patterns','linear; circular; curve; part; feature; face; skip instances','Pattern mounting holes and skip one instance'),
('Reference planes','offset; angle; midplane; points; line-point; tangent','Create an offset plane and rebuild its sketch'),
('Reference axes','points; planes; cylindrical geometry','Create an axis for the turned component'),
('Reference points','coordinates; vertex; curve intersection','Use a reference point as a loft endpoint'),
('Mate connectors in parts','implicit; explicit; origin; orientation','Define a reusable part attachment coordinate system'),
('Variables','length; angle; number; measured; expressions','Drive several bracket features with one thickness variable'),
('Configurations','list; checkbox; numeric; configured properties','Switch between two bracket sizes and validate both'),
('Editable history','edit; suppress; rollback; reorder; undo; redo; preview','Edit an early dimension and rebuild the bracket'),
('Reference repair','provenance; geometric signature; ambiguity; manual repair','Change topology; require repair for an ambiguous face'),
('Derived parts','local source; linked dimensions; placement','Derive a configured part from another local Part Studio'),
('Delete part','part selection','Delete one of two solids without altering the other'),
('Move face','offset; translate; rotate','Offset one planar box face by 2 mm'),
('Replace face','replacement surface; offset','Replace a planar termination with a curved surface'),
('Delete face','heal; cap; open','Remove a fillet face and heal the solid'),
]),
'Surfaces and curves': ('PartStudio/feature_tools.htm', [
('Surface creation','extrude; revolve; sweep; loft','Build open analytic surfaces using each feature'),
('Boundary surface','direction profiles; continuity','Create a four-sided enclosure boundary patch'),
('Fill','edge boundary; guides; continuity','Fill an opening bounded by noncoplanar edges'),
('Surface trim','intersection; keep region','Trim a sheet with a cylindrical tool'),
('Surface extension','distance; termination; continuity','Extend a curved surface to its neighboring sheet'),
('Surface offset','distance; direction','Offset a cylinder surface by 2 mm'),
('Thicken','one-sided; symmetric; solid operations','Thicken the trimmed sheet into a valid 2 mm solid'),
('Surface repair','enclose; stitch/heal; face editing','Close a sewn enclosure and validate its volume'),
('3D fit spline','points; approximation','Create a 3D curve through supplied reference points'),
('Projected curve','two sketches; surface projection','Project a curve onto the enclosure'),
('Bridging curve','endpoints; tangent/curvature continuity','Bridge two edges with tangent end conditions'),
('Composite curve','edge chain; joined curves','Join lines and arcs into a sweep path'),
('Intersection curve','surfaces; sketch regions','Derive the exact intersection of two surfaces'),
('Trim curve','boundaries; intervals','Trim an open 3D curve at a reference plane'),
('Isocline','direction; angle','Compute constant-normal-angle curves on a sphere'),
('Offset curve','distance; surface','Offset a path on a curved sheet'),
('Isoparametric curve','U; V; parameter','Create and edit an isoparametric surface curve'),
('Edit curve','control points; degree; approximation','Modify a spline with endpoint continuity retained'),
('Helix','pitch; revolutions; height; direction; cone/cylinder','Create a 2 mm pitch helix over 20 mm height'),
('Surface analysis','curvature; zebra stripes; draft analysis; deviation','Analyze a known sphere and a drafted enclosure'),
]),
'Assemblies': ('Assembly/assembly.htm', [
('Instances','insert; duplicate; fix; hide; replace','Insert two configured local parts'),
('Subassemblies','nested structure; rigid/flexible','Insert an articulated subassembly'),
('Mate connectors','implicit; explicit; axis orientation','Align part attachment frames with an offset'),
('Fastened mate','zero freedom; offsets','Rigidly attach the bracket base to a plate'),
('Revolute mate','rotation freedom; limits','Hinge an arm with a 0–90 degree limit'),
('Slider mate','translation freedom; limits','Slide a shaft between two axial limits'),
('Cylindrical mate','rotation plus translation; limits','Permit coaxial sliding and rotation'),
('Pin-slot mate','rotation plus slot translation','Connect a pin to an elongated slot'),
('Planar mate','two translations plus rotation','Constrain a part to slide on a plane'),
('Ball mate','three rotations','Connect a ball joint at a fixed center'),
('Parallel mate','axis alignment','Maintain parallel axes with remaining motion'),
('Tangent mate','surface contact','Maintain tangent contact between rolling shapes'),
('Mate limits','minimum; maximum; offsets','Drive a hinge beyond its limit and clamp motion'),
('Relationships','gear; rack-and-pinion; screw; linear','Couple motion at an exact 2:1 ratio'),
('Motion','drag; animation; freedom diagnostics','Animate the articulated assembly over its allowed range'),
('Assembly patterns','linear; circular; instances','Pattern bolts into a circular flange'),
('In-context references','edit part; update context; broken reference repair','Resize a clearance based on another part'),
('Exploded views','steps; translation; rotation; explode lines','Explode and restore an articulated assembly'),
('Interference checks','part pairs; exact overlap','Measure overlap of two intersecting boxes'),
('BOMs','structured; flattened; properties; quantities; exclusion','Export a nested bill of materials with repeated parts'),
]),
'Drawings': ('drawings.htm', [
('Base and projected views','standard; orthographic; isometric; scale','Create front/top/right views of the bracket'),
('Section views','full; half; aligned; offset; associative hatch','Section the turned component through its axis'),
('Detail views','boundary; scale; parent association','Magnify a hole and update its parent part'),
('Auxiliary views','reference edge; orientation','Project a sloped face normal to its surface'),
('Drawing dimensions','linear; angular; radius; diameter; ordinate; baseline; chain','Dimension bracket holes and overall size'),
('Tolerances','symmetric; deviation; limits; geometric; datum','Add a diameter tolerance and a position callout'),
('Annotations','notes; leaders; weld; surface finish; hole/thread callouts','Annotate a threaded bore and machined face'),
('Center marks and lines','circle marks; bolt circles; center lines','Mark hole centers and the turned part axis'),
('Tables','general; BOM; hole; revision; bend; cut list','Place an associative BOM table'),
('Balloons','part/item association; stacked','Balloon each assembly part and retain BOM numbers'),
('Templates','sheet size; border; title block; reusable local templates','Save and reuse an A4 drawing template'),
('Multiple sheets','create; rename; reorder; duplicate','Create two associated sheets and export both'),
('Drawing associativity','parameter update; broken-reference diagnostics','Change bracket thickness and refresh views and dimensions'),
('Drawing PDF export','vector output; sheet selection; units','Export an A4 dimensioned drawing and inspect independently'),
]),
'Specialized modeling': ('PartStudio/feature_tools.htm', [
('Sheet metal creation','extrude; convert; thicken; thickness; bend allowance','Create a 100 × 80 × 40 sheet-metal enclosure'),
('Sheet metal flanges','edge selection; angle; length; alignment; offsets','Add four flanges with a 90 degree bend'),
('Sheet metal bends and relief','bend radius; relief type; corner treatment; joint','Change bend radius and corner relief'),
('Sheet metal edit','tab; hem; jog; bend; unfold/refold; finish','Add a tab and maintain folded/flat association'),
('Folded and flat association','linked geometry; flat features; configurations','Edit a flat cut and verify the folded result'),
('Bend tables','bend directions; angles; radii; export','Export the enclosure bend table and flat DXF'),
('Frames','path; profile orientation; corner treatment','Build a rectangular structural frame'),
('Profile libraries','standard shapes; custom profiles; local reuse','Save and reuse a hollow rectangular profile'),
('Frame trimming','miter; butt; extend; trim to face','Trim a three-member frame junction'),
('Cut lists','length; angle; quantity; grouping; drawing table','Generate a grouped frame cut list'),
('Routing tools','3D routing curve; path editing; filleted corners; routing profiles','Route a tube through three 3D waypoints'),
]),
'Document tools': ('PartStudio/part_studios.htm', [
('Document tabs','Part Studio; Assembly; Drawing; rename; duplicate; reorder','Create a local document containing all three tab types'),
('Units','metric; imperial; conversion; precision','Open a 1 inch part and verify a 25.4 mm measurement'),
('Materials','density; local library; assignment','Assign a known density and verify box mass'),
('Properties','names; metadata; part numbers; configured properties','Edit properties reflected in BOM and drawing title block'),
('Measurement','distance; angle; length; area; radius','Measure analytic box edges and cylinder radius'),
('Mass properties','mass; volume; center of mass; inertia','Check analytic box inertia and centroid'),
('Section views','planes; multiple planes; offsets; reverse','Section the enclosure without changing solid geometry'),
('Local versions','named snapshots; compare; restore','Restore an earlier version without replacing its original'),
('Reusable local libraries','parts; profiles; materials; templates','Reuse a configured local part in another document'),
('Project persistence','ZIP; validation; migration; autosave; recovery; quota handling','Download/reopen the bracket and interrupt an autosave'),
('STEP exchange','import; export; units; exact geometry','Round-trip a box, cylinder and bracket in an independent reader'),
('IGES exchange','import; export; exact surfaces; units','Round-trip trimmed analytic surfaces in an independent reader'),
('STL exchange','import reference mesh; export; explicit closed-mesh conversion','Round-trip an oriented watertight mesh; reject invalid conversion'),
('OBJ exchange','import reference mesh; export; normals; units','Open a reference OBJ and preserve its mesh topology'),
('DXF exchange','documented entity subset; units; clear rejection','Round-trip sketch and drawing entities and reject unsupported entities'),
('SVG exchange','documented entity subset; units; clear rejection','Round-trip supported paths and reject unsupported transforms/entities'),
('Desktop input','mouse; keyboard; precise selection; shortcuts','Complete each milestone workflow using desktop input'),
('Touch input','drawers; touch selection; numeric precision; file handling','Complete bracket editing on physical iOS Safari and Android Chrome'),
('Worker resilience','revision fencing; cancellation; restart; memory cleanup','Cancel a long operation and rebuild from the committed document'),
])}
partials={
'Rectangles':'Only axis-aligned corner rectangle with numeric dimensions', 'Circles':'Only center-radius circle',
'Geometric constraints':'PlaneGCS fixes profile origins and constrains rectangle orientation, dimensions and circle diameter; no general constraint UI',
'Constraint diagnostics':'Solver adapter reports DOF/conflicts/redundancy; arbitrary constraint editing absent',
'Multiple parts':'New-part extrusions/revolutions with stable part IDs', 'Extrude':'Positive blind solid; new/add/remove/intersect; no other terminations or surfaces',
'Revolve':'Angle/full solid about local V axis; new/add/remove/intersect',
'Fillets':'Constant radius on all edges only', 'Chamfers':'Equal distance on all edges only',
'Booleans':'New/add/remove/intersect while extruding/revolving; no standalone tools/keep-tools',
'Editable history':'Edit/suppress/rollback/reorder/delete/undo/redo; full rebuild, no incremental rebuild or preview',
'Units':'Display and numeric input mm/in; internal millimeter geometry',
'Mass properties':'Exact area and volume; no materials/centroid/inertia UI',
'Project persistence':'Version 1 ZIP with JSON/manifest; transactional latest/previous snapshots; no older migrations/assets yet',
'STEP exchange':'Export UI and kernel STEP self-roundtrip test; no import UI/independent STEP reader',
'STL exchange':'Export UI; independent ASCII volume test; no reference mesh import/conversion',
'Desktop input':'Numeric sketch/solid workflow; viewport part selection; keyboard undo/save',
'Touch input':'Responsive drawers/numeric forms and emulated touch workflow; physical devices unverified',
'Worker resilience':'Request/revision protocol, cancel/restart, operation timeout, explicit embind disposal; memory plateau/crash tests pending',
}
rows=[]
for area,(source,tools) in groups.items():
 for name,modes,example in tools:
  key=''.join(c if c.isalnum() else '-' for c in name.lower()).strip('-')
  rows.append({'id':key,'area':area,'tool':name,'source':BASE+source,'documentationReview':'pending',
    'modesToAudit':modes.split('; '),'example':example,
    'acceptance':{'testId':'parity:'+key,'requiredChecks':['Execute every documented mode through the interface',example,'Edit upstream parameters and verify associations','Save/reopen without information loss','Verify failure keeps the last committed document']},
    'status':'partial' if name in partials else 'planned','implementedScope':partials.get(name,''),'passingEvidence':[]})
contract={'baselineDate':'2026-10-09','baselineFrozen':False,'documentationAuditComplete':False,
 'baselineNote':'User capability contract fixed; tool-mode inventory requires audit of linked official documentation and Free eligibility. Mode lists are targets, not claims of exhaustive documented options. No row is complete.',
 'exceptions':['Cloud accounts and collaboration','Proprietary vendor file formats','Execution of existing FeatureScript custom features'], 'rows':rows}
Path('docs/parity.json').write_text(json.dumps(contract,indent=2)+'\n')
md=['# Functional parity register','','Target: Onshape built-in Free CAD workflows on October 9, 2026. The user contract is fixed. The linked-document mode/Free-eligibility audit is **unfinished**; `baselineFrozen` must stay false until reviewed. This register does not claim completed parity.','','The machine-readable source is [parity.json](parity.json). Each row has mode targets, a reproducible workflow, a reserved acceptance ID, evidence, and implementation scope. Reserved test IDs are planned tests, not executable or passing tests. Do not mark a row complete until every audited mode and acceptance check has executable passing evidence.','','| Area | Tool | Status | Reproducible example | Current scope |','|---|---|---|---|---|']
for r in rows:md.append('| '+ ' | '.join([r['area'],r['tool'],r['status'],r['example'],r['implementedScope'] or 'Not implemented'])+' |')
Path('docs/PARITY.md').write_text('\n'.join(md)+'\n')
print(f'{len(rows)} tracked rows; zero complete')
